import json
import os.path
import subprocess
import random
import shutil
from pathlib import Path
from collections import Counter
from tqdm import tqdm
from typing import Dict, List, Any, Set, Tuple

from utilities.data.structure import Structure
from utilities.constants import xxx_to_index, atom_types
from utilities.data.msa import load_a3m_file


# todo script will have to be renamed


def prepare_mmseqs_input(folder_path: str, output_fasta: str):
    """
    Iterates through all .a3m files in the specified folder, extracts the first
    sequence (query sequence) from each, and saves them into a single FASTA file.
    This FASTA file can be used as input for MMseqs2 clustering.

    :param folder_path: Path to the folder containing .a3m files.
    :param output_fasta: Path to the output FASTA file.
    """
    directory = Path(folder_path)
    a3m_files = list(directory.glob("*.a3m"))

    if not a3m_files:
        print(f"No .a3m files found in {folder_path}")
        return

    print(f"Found {len(a3m_files)} .a3m files. Extracting sequences...")

    with open(output_fasta, "w") as f_out:
        for a3m_file in tqdm(a3m_files, desc="Processing A3M files"):
            try:
                sequences = load_a3m_file(str(a3m_file))
                if sequences:
                    # The first sequence is the query sequence
                    query_sequence = sequences[0]

                    # Remove gaps and insertions (lowercase) to get the clean query sequence
                    query_sequence = query_sequence.replace("-", "").replace(".", "")
                    query_sequence = "".join([c for c in query_sequence if not c.islower()])

                    f_out.write(f">{a3m_file.stem}\n")
                    f_out.write(f"{query_sequence}\n")
            except Exception as e:
                print(f"Error processing {a3m_file.name}: {e}")

    print(f"MMseqs2 input FASTA created at: {output_fasta}")


def run_mmseqs_clustering(input_fasta: str, output_prefix: str, min_identity: float = 0.4,
                          coverage: float = 0.8, sensitivity: float = 7.5, verbose=False):
    """
    Executes MMseqs2 'easy-cluster' to group protein sequences by similarity.

    MMseqs2 must be installed and available in the system PATH. This function
    creates a temporary directory for the intermediate MMseqs2 database and
    produces several output files, including a .tsv mapping file.

    :param input_fasta: Path to the FASTA file containing query sequences.
    :param output_prefix: Prefix for the output files (e.g., 'clusters/my_data').
    :param min_identity: Minimum sequence identity threshold (0.0 to 1.0).
                         40% identity is 0.4.
    :param coverage: Minimum alignment coverage threshold (0.0 to 1.0).
                     Default is 0.8 (80% coverage).
    :param sensitivity: Sensitivity parameter for MMseqs2 search. Higher values
                        (up to 7.5) increase sensitivity for distant homologs.
    """
    output_path = Path(output_prefix).absolute()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_dir = output_path.parent / "tmp_mmseqs"

    mmseqs_path = shutil.which("mmseqs")
    if mmseqs_path is None:
        raise FileNotFoundError("The 'mmseqs' binary was not found in the system PATH "
                                "Please install MMseqs2 or provide the binary in the project root.")

    command = [
        mmseqs_path, "easy-cluster",
        input_fasta,
        str(output_path),
        str(tmp_dir),
        "--min-seq-id", str(min_identity),
        "-c", str(coverage),
        "--cov-mode", "0",
        "-s", str(sensitivity)
    ]

    print(f"Running MMseqs2 clustering Using :\n - {' '.join(command)}")

    try:
        result = subprocess.run(command, check=True, capture_output=True, text=True)
        print("    - MMseqs2 clustering completed successfully.")
        if verbose:
            print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"   - Error during MMseqs2 execution:\n{e.stderr}")
        raise

    print(f"   - Removing The Temporary Folder {tmp_dir}")
    if os.path.exists(tmp_dir):
        shutil.rmtree(tmp_dir)


def load_cluster_mapping(tsv_path: str) -> Dict[str, List[str]]:
    """
    Parses the MMseqs2 cluster TSV file and returns a mapping of representatives to members.

    The TSV format is: <representative_id>\t<member_id>

    :param tsv_path: Path to the _cluster.tsv file generated by MMseqs2.
    :return: A dictionary where keys are representative IDs and values are lists of member IDs.
    """

    cluster_mapping = {}
    number_clusters = 0

    with open(tsv_path, "r") as f:

        for line in f:

            parts = line.strip().split("\t")

            if len(parts) != 2:
                continue

            representative, member = parts

            # Append member in one given cluster by the name of one representative
            if representative not in cluster_mapping:
                cluster_mapping[representative] = []
                number_clusters += 1

            cluster_mapping[representative].append(member)

    largest_cluster = max(cluster_mapping, key=lambda x: len(cluster_mapping[x]))

    print(f" - {number_clusters} Clusters")
    print(f" - Largest Cluster : {largest_cluster} > {len(cluster_mapping[largest_cluster])} Proteins")

    return cluster_mapping


def split_data_by_clusters(cluster_mapping: Dict[str, List[str]], train_ratio: float = 0.8,
                           seed: int = 42) -> Tuple[List[str], List[str]]:
    """
    Splits sequences into training and validation sets while keeping clusters intact.

    This ensures that sequences from the same cluster (and thus highly similar)
    do not leak across the train/validation split.

    :param cluster_mapping: Dictionary mapping cluster representatives to member lists.
    :param train_ratio: Proportion of clusters to assign to the training set.
    :param seed: Random seed for reproducibility.
    :return: A tuple containing (train_sequence_ids, validation_sequence_ids).
    """
    random.seed(seed)
    representatives = list(cluster_mapping.keys())
    random.shuffle(representatives)

    split_index = int(len(representatives) * train_ratio)
    train_representatives = representatives[:split_index]
    validation_representatives = representatives[split_index:]

    train_indices = []
    for representative in train_representatives:
        train_indices.extend(cluster_mapping[representative])

    validation_indices = []
    for rep in validation_representatives:
        validation_indices.extend(cluster_mapping[rep])

    print(50*"=")
    print("Data Analysis")
    print(f"Split Complete Number Total Clusters: {len(representatives)}")
    print(f" - {len(train_indices)} Proteins In Train >  {len(train_representatives)}")
    print(f" - {len(validation_indices)} Proteins In Validation > {len(validation_representatives)}")
    print(50*"=")

    return train_indices, validation_indices


def analyze_folder(folder_path: str, output_file: str = "structure_data_summary.json") -> Dict[str, Any]:
    """
    Original analyze_folder implementation (flat dictionary).
    """
    directory = Path(folder_path)
    npz_files = list(directory.glob("*.npz"))

    if not npz_files:
        print(f"No .npz files found in {folder_path}")
        return {}

    summary_dictionary = {}

    for file_path in tqdm(npz_files, desc="Analyzing Structures"):
        file_name = file_path.stem
        try:
            structure = Structure(npz_path=str(file_path))

            number_residues = structure.number_residues
            number_chains = structure.number_chains

            total_atoms = len(structure.atoms)
            missing_atom_count = 0
            unique_present_atoms = set()

            for atom in structure.atoms:
                if atom.is_present:
                    unique_present_atoms.add(atom.name)
                else:
                    missing_atom_count += 1

            missing_atom_percentage = round(100 * missing_atom_count / total_atoms, 2) if total_atoms > 0 else 0

            has_missing_atom = missing_atom_count > 0
            has_chirality = any(atom.chirality != 0 for atom in structure.atoms)
            has_charge = any(atom.charge != 0 for atom in structure.atoms)

            # Residue-level checks
            missing_residue_count = sum(1 for res in structure.residues if not res.is_present)
            missing_residue_percentage = round(100 * missing_residue_count / number_residues,
                                               2) if number_residues > 0 else 0

            non_standard_residues = sorted(list(set(res.name for res in structure.residues if not res.is_standard)))
            has_non_standard_residue = len(non_standard_residues) > 0
            has_non_present_residue = missing_residue_count > 0

            # Structural Gaps
            structural_gaps = 0
            for chain in structure.chains:
                start = chain.residue_start_index
                end = start + chain.residue_count
                chain_residues = structure.residues[start:end]
                for i in range(1, len(chain_residues)):
                    if chain_residues[i].residue_index - chain_residues[i - 1].residue_index > 1:
                        structural_gaps += 1

            # Residue distribution
            if number_residues > 0:
                residue_counts = Counter(res.name for res in structure.residues)
                residue_distribution = {
                    res_name: round(100 * count / number_residues, 2)
                    for res_name, count in residue_counts.items()
                }
            else:
                residue_distribution = {}

            # Store in summary dictionary (Original Flat Format)
            summary_dictionary[file_name] = {
                "number_residues": number_residues,
                "number_chains": number_chains,
                "has_missing_atom": has_missing_atom,
                "missing_atom_percentage": missing_atom_percentage,
                "unique_present_atoms": sorted(list(unique_present_atoms)),
                "has_chirality": has_chirality,
                "has_charge": has_charge,
                "has_non_standard_residue": has_non_standard_residue,
                "non_standard_residue_names": non_standard_residues,  # Added suggestion
                "has_non_present_residue": has_non_present_residue,
                "missing_residue_percentage": missing_residue_percentage,
                "structural_gaps": structural_gaps,
                "residue_distribution": residue_distribution
            }

        except Exception as e:
            print(f"\nError processing {file_name}: {e}")

    with open(output_file, 'w') as f:
        json.dump(summary_dictionary, f, indent=4)

    return summary_dictionary


def analyze_summary_json(json_path: str, threshold: float = 20.0):
    """
    Reads the summary JSON and computes all requested statistics without reading NPZ files.
    """
    with open(json_path, 'r') as f:
        data = json.load(f)

    all_observed_residues = set()
    all_observed_atoms = set()
    high_dist_count = 0
    total_structures = len(data)

    all_non_standard_found = set()

    for struct_id, info in data.items():
        # Collect residues from distribution keys
        dist = info.get("residue_distribution", {})
        all_observed_residues.update(dist.keys())

        # Check high distribution threshold
        if any(pct > threshold for pct in dist.values()):
            high_dist_count += 1

        # Collect atoms
        atoms = info.get("unique_present_atoms", [])
        all_observed_atoms.update(atoms)

        # Track non-standard residue names if available
        non_std = info.get("non_standard_residue_names", [])
        all_non_standard_found.update(non_std)

    # Vocabulary checks
    supported_residues = set(xxx_to_index.keys())
    supported_atoms = set(atom_types)

    missing_residues = sorted(list(all_observed_residues - supported_residues))
    missing_atoms = sorted(list(all_observed_atoms - supported_atoms))

    high_dist_pct = round(100 * high_dist_count / total_structures, 2) if total_structures > 0 else 0

    # Print Report
    print("\n" + "=" * 50)
    print(f"JSON SUMMARY ANALYSIS: {json_path}")
    print("=" * 50)
    print(f"Total Structures in JSON: {total_structures}")

    print("\n--- Vocabulary Coverage (Missing from constants.py) ---")
    print(f"Missing Residues: {missing_residues if missing_residues else 'None'}")
    print(f"Missing Atoms:    {missing_atoms if missing_atoms else 'None'}")

    print("\n--- Distribution Statistics ---")
    print(f"Structures with any residue >{threshold}%: {high_dist_pct}%")

    if all_non_standard_found:
        print("\n--- Non-Standard Residues Identified ---")
        print(f"Names: {sorted(list(all_non_standard_found))}")

    print("=" * 50 + "\n")

    return {
        "missing_residues": missing_residues,
        "missing_atoms": missing_atoms,
        "high_dist_pct": high_dist_pct
    }
