ExperimentConfiguration:
  experiment_parent_folder: "/home/robert_kelevra/Data/protein_project/protein_experiments"
  experiment_name: "experiment_0"
  data_folder: "/home/robert_kelevra/Projects/protein-structures/data_examples/openfold"
  configuration_path: "/home/robert_kelevra/Projects/protein-structures/configurations/tiny_configuration.yaml"
  train_split_file: "/home/robert_kelevra/Projects/protein-structures/dataset_splits/Train_small.json"
  validation_split_file: "/home/robert_kelevra/Projects/protein-structures/dataset_splits/Validation_small.json"
  test_split_file: "/home/robert_kelevra/Projects/protein-structures/dataset_splits/Test_small.json"
  information_dump: 100
  weight_saving_iterations: 500
  number_iterations: 50000
  compute_validation_iteration: true
  learning_rate: 1.0e-3
  dtype: "float64"
  resume_training: false
