import json
import os.path
import subprocess
import random
import shutil
from pathlib import Path
from collections import Counter
from tqdm import tqdm
from typing import Dict, List, Any, Set, Tuple

from utilities.data.structure import Structure
from utilities.constants import xxx_to_index, atom_types
from utilities.data.msa import load_a3m_file

def prepare_mmseqs_input(folder_path: str, output_fasta: str):
    """
    Iterates through all .a3m files in the specified folder, extracts the first
    sequence (query sequence) from each, and saves them into a single FASTA file.
    This FASTA file can be used as input for MMseqs2 clustering.

    :param folder_path: Path to the folder containing .a3m files.
    :param output_fasta: Path to the output FASTA file.
    """
    directory = Path(folder_path)
    a3m_files = list(directory.glob("*.a3m"))

    if not a3m_files:
        print(f"No .a3m files found in {folder_path}")
        return

    print(f"Found {len(a3m_files)} .a3m files. Extracting sequences...")

    with open(output_fasta, "w") as f_out:
        for a3m_file in tqdm(a3m_files, desc="Processing A3M files"):
            try:
                sequences = load_a3m_file(str(a3m_file))
                if sequences:
                    # The first sequence is the query sequence
                    query_sequence = sequences[0]

                    # Remove gaps and insertions (lowercase) to get the clean query sequence
                    query_sequence = query_sequence.replace("-", "").replace(".", "")
                    query_sequence = "".join([c for c in query_sequence if not c.islower()])

                    f_out.write(f">{a3m_file.stem}\n")
                    f_out.write(f"{query_sequence}\n")
            except Exception as e:
                print(f"Error processing {a3m_file.name}: {e}")

    print(f"MMseqs2 input FASTA created at: {output_fasta}")


def run_mmseqs_clustering(input_fasta: str, output_prefix: str, min_identity: float = 0.4,
                          coverage: float = 0.8, sensitivity: float = 7.5, verbose=False):
    """
    Executes MMseqs2 'easy-cluster' to group protein sequences by similarity.

    MMseqs2 must be installed and available in the system PATH. This function
    creates a temporary directory for the intermediate MMseqs2 database and
    produces several output files, including a .tsv mapping file.

    :param input_fasta: Path to the FASTA file containing query sequences.
    :param output_prefix: Prefix for the output files (e.g., 'clusters/my_data').
    :param min_identity: Minimum sequence identity threshold (0.0 to 1.0).
                         40% identity is 0.4.
    :param coverage: Minimum alignment coverage threshold (0.0 to 1.0).
                     Default is 0.8 (80% coverage).
    :param sensitivity: Sensitivity parameter for MMseqs2 search. Higher values
                        (up to 7.5) increase sensitivity for distant homologs.
    """
    output_path = Path(output_prefix).absolute()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_dir = output_path.parent / "tmp_mmseqs"

    mmseqs_path = shutil.which("mmseqs")
    if mmseqs_path is None:
        raise FileNotFoundError("The 'mmseqs' binary was not found in the system PATH "
                                "Please install MMseqs2 or provide the binary in the project root.")

    command = [
        mmseqs_path, "easy-cluster",
        input_fasta,
        str(output_path),
        str(tmp_dir),
        "--min-seq-id", str(min_identity),
        "-c", str(coverage),
        "--cov-mode", "0",
        "-s", str(sensitivity)
    ]

    print(f"Running MMseqs2 clustering Using :\n - {' '.join(command)}")

    try:
        result = subprocess.run(command, check=True, capture_output=True, text=True)
        print("    - MMseqs2 clustering completed successfully.")
        if verbose:
            print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"   - Error during MMseqs2 execution:\n{e.stderr}")
        raise

    print(f"   - Removing The Temporary Folder {tmp_dir}")
    if os.path.exists(tmp_dir):
        shutil.rmtree(tmp_dir)


def load_cluster_mapping(tsv_path: str) -> Dict[str, List[str]]:
    """
    Parses the MMseqs2 cluster TSV file and returns a mapping of representatives to members.

    The TSV format is: <representative_id>\t<member_id>

    :param tsv_path: Path to the _cluster.tsv file generated by MMseqs2.
    :return: A dictionary where keys are representative IDs and values are lists of member IDs.
    """

    cluster_mapping = {}
    number_clusters = 0

    with open(tsv_path, "r") as f:

        for line in f:

            parts = line.strip().split("\t")

            if len(parts) != 2:
                continue

            representative, member = parts

            # Append member in one given cluster by the name of one representative
            if representative not in cluster_mapping:
                cluster_mapping[representative] = []
                number_clusters += 1

            cluster_mapping[representative].append(member)

    largest_cluster = max(cluster_mapping, key=lambda x: len(cluster_mapping[x]))

    print(f" - {number_clusters} Clusters")
    print(f" - Largest Cluster : {largest_cluster} > {len(cluster_mapping[largest_cluster])} Proteins")

    return cluster_mapping


def split_data_by_clusters(cluster_mapping: Dict[str, List[str]], output_folder: str,
                           train_ratio: float = 0.8, seed: int = 42) -> Tuple[List[str], List[str]]:
    """
    Splits sequences into training and validation sets while keeping clusters intact.

    This ensures that sequences from the same cluster (and thus highly similar)
    do not leak across the train/validation split.

    :param cluster_mapping: Dictionary mapping cluster representatives to member lists.
    :param output_folder: Folder where Train.json and Validation.json will be saved.
    :param train_ratio: Proportion of clusters to assign to the training set.
    :param seed: Random seed for reproducibility.
    :return: A tuple containing (train_sequence_ids, validation_sequence_ids).
    """
    random.seed(seed)
    representatives = list(cluster_mapping.keys())
    random.shuffle(representatives)

    split_index = int(len(representatives) * train_ratio)
    train_representatives = representatives[:split_index]
    validation_representatives = representatives[split_index:]

    train_clusters = {rep: cluster_mapping[rep] for rep in train_representatives}
    validation_clusters = {rep: cluster_mapping[rep] for rep in validation_representatives}

    # Save to JSON files
    output_path = Path(output_folder)
    output_path.mkdir(parents=True, exist_ok=True)

    with open(output_path / "Train.json", "w") as f:
        json.dump(train_clusters, f, indent=4)

    with open(output_path / "Validation.json", "w") as f:
        json.dump(validation_clusters, f, indent=4)

    train_indices = []
    for representative in train_representatives:
        train_indices.extend(cluster_mapping[representative])

    validation_indices = []
    for rep in validation_representatives:
        validation_indices.extend(cluster_mapping[rep])

    print(50*"=")
    print("Data Analysis")
    print(f"Split Complete Number Total Clusters: {len(representatives)}")
    print(f" - {len(train_indices)} Proteins In Train >  {len(train_representatives)}")
    print(f" - {len(validation_indices)} Proteins In Validation > {len(validation_representatives)}")
    print(50*"=")

    return train_indices, validation_indices

